### ISSUE TITLE
code review

### ISSUE THREAD

**Issue by AwaitingIrindul** [PolytechLyon/isi3-tp4-kebab-kata-isi3-tp4-regnard-marchand#2]
Bonjour, 

Peut-on avoir une revue de code pour ce projet ? 😃

**Comment by k33g** [comment]
Bonjour @AwaitingIrindul 

- Le rapport est trop léger
- l'avantage des streams c'est par rapport à l'exercice, pas "en général"

**Comment by AwaitingIrindul** [comment]
👋 @k33g, 

Nous avons modifié le rapport.

**Comment by AwaitingIrindul** [comment]
Bonjour @k33g, peut-on fermer cette issue ou d'autres modifications sont à apporter ?
